// Export shared infrastructure
export { TerminalCommand } from './shared/terminal-command.js'
export { writeStdout, writelnStdout, writeStderr, writelnStderr } from './shared/helpers.js'
export type { CommandArgs } from './shared/command-args.js'

// The legacy-command shim -- see legacy-command-shim.ts's own doc comment for why this replaced
// the old eager createAllCommands/TerminalCommands (deleted here; its only consumers, kernel.ts's
// registerCommands/executeCommand and terminal.ts's tab-completion, all moved off it).
export { getLegacyCommands, resolveLegacyCommand } from './shared/legacy-command-shim.js'
export type { LegacyCommands, LegacyCommandEntry, CreateCommandFn } from './shared/legacy-command-shim.js'

// Export individual command factories -- excludes the 38 execve-migrated names (echo, basename,
// dirname, tr, mkdir, rm, cp, mv, touch, chmod, cat, head, tail, wc, nl, rev, tac, uniq, cut, fold,
// expand, unexpand, cksum, strings, xxd, od, hash, cmp, comm, column, seq, factor, rmdir, join,
// paste, sleep, mktemp, shuf) and the 8 true shell builtins now living in
// core/kernel/src/tree/lib/shell-builtins.ts (cd, set, bg, fg, jobs, wait, local, env) -- neither
// has a createCommand anymore, only meta (see their files).
export { createCommand as createAwk } from './commands/awk.js'
export { createCommand as createCal } from './commands/cal.js'
export { createCommand as createChown } from './commands/chown.js'
export { createCommand as createCron } from './commands/cron.js'
export { createCommand as createCrypto } from './commands/crypto.js'
export { createCommand as createCurl } from './commands/curl.js'
export { createCommand as createDate } from './commands/date.js'
export { createCommand as createDd } from './commands/dd.js'
export { createCommand as createDiff } from './commands/diff.js'
export { createCommand as createFalse } from './commands/false.js'
export { createCommand as createFetch } from './commands/fetch.js'
export { createCommand as createFind } from './commands/find.js'
export { createCommand as createFmt } from './commands/fmt.js'
export { createCommand as createFormat } from './commands/format.js'
export { createCommand as createGit } from './commands/git.js'
export { createCommand as createGrep } from './commands/grep.js'
export { createCommand as createGroups } from './commands/groups.js'
export { createCommand as createHistory } from './commands/history.js'
export { createCommand as createHostname } from './commands/hostname.js'
export { createCommand as createId } from './commands/id.js'
export { createCommand as createLess } from './commands/less.js'
export { createCommand as createLn } from './commands/ln.js'
export { createCommand as createLoadCrontab } from './commands/load-crontab.js'
export { createCommand as createLs } from './commands/ls.js'
export { createCommand as createMan } from './commands/man.js'
export { createCommand as createMotd } from './commands/motd.js'
export { createCommand as createMount } from './commands/mount.js'
export { createCommand as createNc } from './commands/nc.js'
export { createCommand as createNproc } from './commands/nproc.js'
export { createCommand as createOpen } from './commands/open.js'
export { createCommand as createPasskey } from './commands/passkey.js'
export { createCommand as createPlay } from './commands/play.js'
export { createCommand as createPr } from './commands/pr.js'
export { createCommand as createPrintf } from './commands/printf.js'
export { createCommand as createPwd } from './commands/pwd.js'
export { createCommand as createReadlink } from './commands/readlink.js'
export { createCommand as createRealpath } from './commands/realpath.js'
export { createCommand as createScreensaverDaemon } from './commands/screensaver-daemon.js'
export { createCommand as createSed } from './commands/sed.js'
export { createCommand as createSockets } from './commands/sockets.js'
export { createCommand as createSort } from './commands/sort.js'
export { createCommand as createSplit } from './commands/split.js'
export { createCommand as createStat } from './commands/stat.js'
export { createCommand as createTar } from './commands/tar.js'
export { createCommand as createTee } from './commands/tee.js'
export { createCommand as createTest } from './commands/test.js'
export { createCommand as createTheme } from './commands/theme.js'
export { createCommand as createTime } from './commands/time.js'
export { createCommand as createTrue } from './commands/true.js'
export { createCommand as createTty } from './commands/tty.js'
export { createCommand as createUmount } from './commands/umount.js'
export { createCommand as createUname } from './commands/uname.js'
export { createCommand as createUnzip } from './commands/unzip.js'
export { createCommand as createUptime } from './commands/uptime.js'
export { createCommand as createUser } from './commands/user.js'
export { createCommand as createVideo } from './commands/video.js'
export { createCommand as createView } from './commands/view.js'
export { createCommand as createVim } from './commands/vim.js'
export { createCommand as createWeb } from './commands/web.js'
export { createCommand as createWhich } from './commands/which.js'
export { createCommand as createWhoami } from './commands/whoami.js'
export { createCommand as createZip } from './commands/zip.js'
